version: "3.7"
services:
  mcserver:
    image: itzg/minecraft-server:java17-alpine
    container_name: mcserver
    env_file: .env
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - "./data:/data"
      - "./modpack:/modpack"
      - "./mods:/mods"
      - "./datapacks:/datapacks"
      - "./config:/config"
      - "./config/carpet.conf:/data/world/carpet.conf"
      - "./config/carpet-fixes.conf:/data/world/carpet-fixes.conf"
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 1m
      retries: 20
    networks:
      - internal
  proxy:
    image: wernight/ngrok
    container_name: proxy
    env_file: .env
    environment:
      - NGROK_PROTOCOL=TCP
      - NGROK_PORT=mcserver:${PORT}
    networks:
      - internal
networks:
  internal:
    driver: bridge
